# just a little makefile to store repreatitive task

#################################################################################
#		chatandfight								#
#################################################################################

build:
	zip -r chatandfight.zip chatandfight_src
	
clean:
	rm -rf chatandfight.zip
