# just a little makefile to store repreatitive task

#################################################################################
#		mmo3d								#
#################################################################################

build:
	zip -r mmo3d.zip src
	
clean:
	rm -rf mmo3d.zip
